# Generated by Django 5.2.5 on 2025-09-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_created_at_product_is_discounted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_discounted',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('jersey', 'Jersey'), ('sepatu', 'Sepatu'), ('aksesoris', 'Aksesoris'), ('peralatan', 'Peralatan Olahraga'), ('lainnya', 'Lainnya')], max_length=100),
        ),
    ]
